### ISSUE TITLE
Change the default route '/admin'

### ISSUE THREAD

**Issue by ljfreelancer88** [sulu/skeleton#65]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no

Hi, how can I change the default route `'/admin'`? Instead of https://domain.io/admin, I want it to be https://domain.io/custom-url-for-admin.

Thanks in advance

**Comment by alexander-schranz** [comment]
You need to adjust the admin `config/routes` admin fiels , `config/packages/security_admin.yaml`, `public/index.php` and need to set the correct cookie path in `config/packages/framework_admin.yaml`.

Have also a look at the following issue, not all changes there necessary for only changing the admin url: https://github.com/sulu/sulu-docs/issues/495

**Comment by ljfreelancer88** [comment]
That's a lot of files to change :) I got breach alert from Chrome though. I have to switched back.

Is it possible to have this in the configuration? Or there's a command that does this.

**Comment by alexander-schranz** [comment]
No there is no command as its uncommon:

See https://github.com/sulu/sulu-demo/pull/60/files als example.

**Comment by alexander-schranz** [comment]
I'm closing this issue if you run into any problems feel free to comment here or join our [slack channel](https://sulu.io/services-and-support)

**Comment by Nyholm** [comment]
Oh, the cookie path and fragment path was tricky to find. I did not expect Sulu to set these for me.

**Comment by alexander-schranz** [comment]
@Nyholm Thank you for the feedback. We had problems that the website session did logout the admin users and other way around, so we need to configure a different session path for the admin. The fragment path is required because of the 2 kernel setup that admin fragments hit the admin kernel. We are working on getting sulu to a 1 Kernel setup so this 2 tricky configuration should hopefully be gone in the next major release.
